config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/about',   to: 'static_pages#about'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
 
  resources :units, only: [:show, :index]
  resources :topics, only: [:show, :index]
  resources :tips
  resources :lessons, only: [:show, :index] do 
    resources :tips 
  end 
  resources :users do 
    resources :tips, only: [:index]
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :unit 
  belongs_to :topic 
  has_and_belongs_to_many :tips 
  

end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :tip 
  belongs_to :user 

end

app/models/tip.rb
class Tip < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :lessons  
  
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :unit 
  has_many :lessons 
  
end 

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :topics 
  has_many :lessons 
end 

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tips
  belongs_to :user_role 
end

app/models/user_role.rb
class UserRole < ApplicationRecord 
  has_many :users 
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
require 'pry'
class SessionsController < ApplicationController
  def new
    @user = User.new
    @users = User.all
  end

  def facebook_create
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.uid = auth['uid']
      pwd = SecureRandom.hex #To bypass validations for password set up in user model
      u.password = pwd 
      u.password_confirmation = pwd
    end
    
    log_in(@user)
    redirect_to @user
 
  end 

  def github_create 
    #Github OmniAuth Implementation 
    
    @user = User.find_or_create_by(uid: auth['uid']) do |user|  
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["extra"]["raw_info"]["login"] 
      user.email = Faker::Internet.email
      pwd = SecureRandom.hex #To bypass validations for password set up in user model
      user.password = pwd 
      user.password_confirmation = pwd
    end

    log_in(@user)
    redirect_to @user
  end 


  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  private
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home 
  end 

  def about 
  end 
  
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.fetch(:tip, {})
    end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index 
  end 
  
  def show 
  end 

end 

app/controllers/users_controller.rb
require 'pry'
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.user_role = "standard"
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        if session[:user_id]
          @current_user ||= User.find_by(id: session[:user_id])  # Same as @current_user = @current_user || User.find_by(id: session[:user_id])
        end 
      end
    
      def logged_in?
         !current_user.nil?
      end 
      
      def log_out
        session.delete(:user_id)
        @current_user = nil
      end
    
      def log_in(user)
        session[:user_id] = user.id
      end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark">
 <div class="container col-lg-8 offset-col-2" >
 <a id="logo" class="navbar-brand" href="#"><span id="slash_slash">//</span>learnHELP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item">
        <a class="nav-link" href="<%=root_path%>">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-light" href="<%= lessons_path %>">Coding Topics</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link text-light" href="<%= tips_path%>">Best Tips</a>
      </li>
    </ul>
    
    <% if logged_in? %>
    <div id="dropdown_marker" class="block-inline my-2 my-lg-0 dropdown-toggle btn-group navbar-dark"  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <button id="account_icon" class="fa fa-user-circle "></button>
      <div id="test" class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item nav-item text-light" %>
      </div>
       </div>
    <% else %>
    <div class="block-inline my-2 my-lg-0">
      <a id="icon_header" class="fa fa-sign-in">Sign In</a>
    <% end %>
    </div>
    
 
  <div id="login_target">
    <%= render 'sessions/form', :locals => {:class_display => "none"} %>
  </div>
  </div>
</nav>




<script>

$(function(){
  $('a.nav-link').each(function() {
    if ($(this).prop('href') == window.location.href) {
      $(this).addClass('current');
    }
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironCapstoneProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
  <div class="center jumbotron text-center">
    <h1>Welcome to LearnHELP</h1>

    <h2>
      A place for students to provide targeted tips to others feeling the pain of learning something new. 
    </h2>
<button class = "standard-input-button">
    <%=link_to "Sign up now!", signup_path%>
</button><br><br>


<a href="/auth/facebook" class="btn btn-sm btn-social btn-facebook">
  <span class="fa fa-facebook"></span>
  Sign in with Facebook
</a>

<a href="/auth/github" class="btn btn-sm btn-social btn-github">
  <span class="fa fa-github"></span>
  Sign in with Github
</a>


  </div>
   <h3 id='plug'>What is the Flatiron School?  Who are you people? Check it out!     
  <%= link_to image_tag("learn.png", alt: "Learn Link"),
              'https://flatironschool.com/' %></h3>

app/views/tips/_form.html.erb
<%= form_with(model: tip, local: true) do |form| %>
  <% if tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<h1>Editing Tip</h1>

<%= render 'form', tip: @tip %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tips</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tips.each do |tip| %>
      <tr>
        <td><%= link_to 'Show', tip %></td>
        <td><%= link_to 'Edit', edit_tip_path(tip) %></td>
        <td><%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tip', new_tip_path %>

app/views/tips/new.html.erb
<h1>New Tip</h1>

<%= render 'form', tip: @tip %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => "form"} do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :username, class: "col-sm-4 control-label"  %>
    <%= form.text_field :username, class: "form-control col-sm-4" %>
  </div>

  <div class="form-group">
    <%= form.label :email, class: "col-sm-4 control-label"  %>
    <%= form.text_field :email, class: "form-control col-sm-4" %>
  </div>

  <div class="form-group">
    <%= form.label :password, class: "col-sm-4 control-label"  %>
    <%= form.text_field :password, class: "form-control col-sm-4" %>
  </div>
  
  <div class="form-group">
    <%= form.label :password_confirmation, class: "col-sm-4 control-label"  %>
    <%= form.text_field :password_confirmation, class: "form-control col-sm-4" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>